### ISSUE TITLE
Enable plugin for single server/location only

### ISSUE THREAD

**Issue by flo-mic** [coreruleset/phpmyadmin-rule-exclusions-plugin#1]
First of all many thanks for the great job the whole crs team is doing to make the web more secure!

I just found this plugin and would like to try it on my system. Is there any possibility to enable the plugin only on server/location level? In the old rule implementation there is the possibility to enable it with the variable `crs_exclusions_phpmyadmin` which allowed to enable it in specific directives only. Do you plan to support this here as well? 

This is a very specific plugin and should be only enabled on the server/location where it is needed. On the other plugins this configuration option was not needed as they are for the general server protection, but I believe most users have also other websites on the web server where this exclusion rules could be a security risk.

**Comment by lifeforms** [comment]
Hi @flo-mic,

You can limit the uses of the phpmyadmin exclusion package, for instance by activating it only in the certain <VirtualHost>.

```
SecAction \
 "id:123456,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.crs_exclusions_phpmyadmin=1"
```

It's also possible to only activate it on certain paths - if you use Apache it can be done within a `<Location>`.

**Comment by lifeforms** [comment]
Sorry, I replied to you, but my solution only was relevant for CRS 3.3.x. Hopefully somebody else has a good solution for your problem. Otherwise we will take it to our next meeting.

**Comment by RedXanadu** [comment]
I think we should keep the new plugin repositories private until they are officially released with CRS 4, to prevent confusion (otherwise we have two lots of REs officially available at once…)

Personally, I would put such a configuration in its own `<VirtualHost>` section, e.g. a WordPress only section with the WordPress RE plugin enabled.

@flo-mic For the avoidance of doubt, this rule exclusion plugin is _the same as the one you can currently get in the official CRS release_ using the `crs_exclusions_phpmyadmin` variable, so you can get exactly the same effect by using it in, say, v3.3.2 as usual.

**Comment by RedXanadu** [comment]
For context, the CRS official documentation currently advises the following:

> **Tip**
>
> If running multiple web applications, it is highly recommended to enable a rule exclusion package only for the location where the corresponding web application resides. For example, to enable the WordPress rule exclusion package only for locations under ‘/wordpress’, a rule like the following could be used:
>
> `SecRule REQUEST_URI "@beginsWith /wordpress/" setvar:tx.crs_exclusions_wordpress=1...`

**Comment by dune73** [comment]
That is correct. We do not have this option when people want to restrict plugins / RE-plugins to individual hosts.

Moving REs to plugins is still the right move, but it does not really allow us to make them more flexbile with the use of Startup time exclusions.

**Comment by azurit** [comment]
I think we should implement this feature (and i'm sure @airween will agree with me). @dune73 I asked you this some time ago in some other discussion but you didn't reply: Are there any technical problems why this cannot be implemented?

**Comment by dune73** [comment]
Yes, true. I did not respond. Sorry.

The problem is this is applied context-wide. So either you load the rules / plugins on the server and then it's applied everywhere. Or you load it on the VH, and then you duplicate the rule base. Technically, that works AFAICT (but I do not run it in prod like this), but ModSecurity is known to produce memory leaks this way and hosters run thousands of VHs on the same server, so it's kind of annoying ...

**Comment by flo-mic** [comment]
@dune73 @azurit not sure if this is the right approach. But I combined the plugin and rule based implementation in my pgadmin plugin (https://github.com/flo-mic/pgadmin-rule-exclusions-plugin)

I think a option to enable/disable a plugin is not needed for every plugin. If we have a application specific plugin like pgadmin or phpmyadmin this option should be available. On generic plugins like antivirus or fake-bot detection it might not be required. Therefore the generic plugins can still use features like `SecRuleUpdateTargetByTag`.

**Comment by azurit** [comment]
@dune73 Why we cannot implement a configuration option which can be used to disable a plugin?

I think enable/disable is needed only for RE plugins like phpmyadmin, as @flo-mic already stated.

**Comment by azurit** [comment]
This should be implemented, can you confirm @flo-mic ?

**Comment by flo-mic** [comment]
Yes, it's implemented with latest plugin change. Thanks
